from typing import List, Dict


OCTAVE: Dict[str, List] = {
    "Do-Ra-Mi": [
        "Do",
        "Do-diesis",
        "Re",
        "Re-diesis",
        "Mi",
        "Fa",
        "Fa-diesis",
        "Sol",
        "Sol-diesis",
        "La",
        "La-diesis",
        "Si",
    ],
    "Sa-Re-Ga (English)": [
        "Sa",
        "Re-Komal",
        "Re",
        "Ga-Komal",
        "Ga",
        "Ma",
        "Ma-Tivra",
        "Pa",
        "Dha-Komal",
        "Dha",
        "Ni-Komal",
        "Ni",
    ],
    "Sa-Re-Ga (Hindi)": [
        "सा",
        "रे॒",
        "रे",
        "ग॒",
        "ग",
        "म",
        "म॑",
        "प",
        "ध॒",
        "ध",
        "नि॒",
    ],
}
